# Generated by Django 5.1.3 on 2024-11-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='streetAddress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
