# Generated by Django 5.1.1 on 2024-11-17 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0006_alter_lease_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackId', models.AutoField(primary_key=True, serialize=False)),
                ('submissionDate', models.DateField(auto_now_add=True)),
                ('starRating', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('leaseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leases.lease')),
                ('tenantId', models.ForeignKey(limit_choices_to={'role': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
