# Generated by Django 5.1.1 on 2024-11-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed')], default='new', max_length=10),
        ),
    ]
