# Generated by Django 5.1.1 on 2024-12-07 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_status'),
        ('properties', '0008_property_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='leaseId',
        ),
        migrations.AddField(
            model_name='feedback',
            name='propertyId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
