# Generated by Django 5.1.1 on 2024-11-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=50)),
                ('number_of_rooms', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('leased', 'Leased')], default='available', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('listing_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
