# Generated by Django 5.1.1 on 2024-11-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_is_furnished_property_num_of_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
