# Generated by Django 5.1.3 on 2024-11-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_pet_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='pet_policy',
            field=models.CharField(choices=[('allowed', 'Allowed'), ('not_allowed', 'Not Allowed')], default='not_allowed', max_length=11),
        ),
    ]
