# Generated by Django 5.1.1 on 2024-11-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='lease',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
