# Generated by Django 5.1.1 on 2024-11-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0004_lease_status_lease_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10),
        ),
    ]
