# Generated by Django 5.1.1 on 2024-11-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0005_lease_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated'), ('pending', 'Pending')], default='active', max_length=10),
        ),
    ]
