# Generated by Django 5.1.1 on 2024-11-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0006_alter_lease_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
