# Generated by Django 5.1.1 on 2024-12-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='subject',
            field=models.TextField(default=''),
        ),
    ]
