# Generated by Django 5.1.1 on 2024-11-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='lease_id',
            new_name='leaseId',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='tenant_id',
            new_name='tenantId',
        ),
    ]
