# Generated by Django 5.1.1 on 2024-11-02 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease_management', '0001_initial'),
        ('rent_payment', '0002_rename_lease_id_payment_leaseid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='leaseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease_management.lease'),
        ),
    ]
