# Generated by Django 5.1.1 on 2024-11-16 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0004_lease_status_lease_total_amount'),
        ('rent_payment', '0004_alter_payment_paymentmethod_alter_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='leaseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leases.lease'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenantId',
            field=models.ForeignKey(limit_choices_to={'role': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
