# Generated by Django 5.1.1 on 2024-11-17 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_payment', '0005_alter_payment_leaseid_alter_payment_tenantid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
